"""initial schema

Revision ID: 646e896e3664
Revises:
Create Date: 2026-08-15 22:53:52.740852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '646e896e3664'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('machine_type', sa.String(length=64), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'UNKNOWN', name='machinestatusenum'), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_machine_code'), 'machines', ['machine_code'], unique=True)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ENGINEER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('parameter_key', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('condition_description', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('suggested_action', sa.String(length=512), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_machine_id'), 'alerts', ['machine_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faults',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('fault_type', sa.String(length=128), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faults_machine_id'), 'faults', ['machine_id'], unique=False)
    op.create_table('machine_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('parameter_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('normal_min', sa.Float(), nullable=True),
    sa.Column('normal_max', sa.Float(), nullable=True),
    sa.Column('warning_min', sa.Float(), nullable=True),
    sa.Column('warning_max', sa.Float(), nullable=True),
    sa.Column('critical_min', sa.Float(), nullable=True),
    sa.Column('critical_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_parameters_machine_id'), 'machine_parameters', ['machine_id'], unique=False)
    op.create_table('machine_status',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('condition', sa.Enum('HEALTHY', 'DEGRADED', 'WARNING', 'CRITICAL', 'UNKNOWN', name='healthcondition'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue', sa.String(length=512), nullable=False),
    sa.Column('detected_fault', sa.String(length=128), nullable=True),
    sa.Column('action_taken', sa.String(length=1024), nullable=True),
    sa.Column('technician', sa.String(length=128), nullable=True),
    sa.Column('parts_replaced', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('downtime_minutes', sa.Float(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_machine_id'), 'maintenance_records', ['machine_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('training_dataset_id', sa.UUID(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'ACTIVE', 'ARCHIVED', 'FAILED', name='modelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('sensor_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'INVALID', 'STALE', name='sensorstatus'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['machine_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_machine_id'), 'sensors', ['machine_id'], unique=False)
    op.create_index(op.f('ix_sensors_parameter_id'), 'sensors', ['parameter_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('triggering_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_machine_id'), 'anomalies', ['machine_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_model_id'), 'model_metrics', ['model_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.Enum('ANOMALY', 'FAULT_CLASSIFICATION', 'RUL', name='predictiontype'), nullable=False),
    sa.Column('predicted_fault', sa.String(length=128), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_data_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_data_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_machine_id'), 'predictions', ['machine_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('parameter_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.Enum('VALID', 'INVALID', 'MISSING', 'SUSPECT', 'SIMULATED', name='dataquality'), nullable=False),
    sa.Column('source', sa.Enum('REAL', 'SIMULATED', 'DATASET_REPLAY', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_readings_machine_param_time', 'sensor_readings', ['machine_id', 'parameter_key', 'timestamp'], unique=False)
    op.create_table('maintenance_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_text', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_recommendations_machine_id'), 'maintenance_recommendations', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_recommendations_machine_id'), table_name='maintenance_recommendations')
    op.drop_table('maintenance_recommendations')
    op.drop_index('ix_readings_machine_param_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_predictions_machine_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_metrics_model_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_anomalies_machine_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_sensors_parameter_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_machine_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_maintenance_records_machine_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_table('machine_status')
    op.drop_index(op.f('ix_machine_parameters_machine_id'), table_name='machine_parameters')
    op.drop_table('machine_parameters')
    op.drop_index(op.f('ix_faults_machine_id'), table_name='faults')
    op.drop_table('faults')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_alerts_machine_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_machines_machine_code'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
