"""phase 2 parameter config hardening

Revision ID: edaaf33b1df3
Revises: 646e896e3664
Create Date: 2026-08-17 10:46:45.324176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edaaf33b1df3'
down_revision: Union[str, None] = '646e896e3664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_calibrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calibrated_by', sa.String(length=128), nullable=True),
    sa.Column('calibration_method', sa.String(length=256), nullable=True),
    sa.Column('reference_standard', sa.String(length=256), nullable=True),
    sa.Column('offset_applied', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_calibrations_sensor_id'), 'sensor_calibrations', ['sensor_id'], unique=False)
    # NOTE: manually added — autogenerate does not emit CREATE TYPE for an
    # Enum added to an *existing* table via a standalone add_column (only
    # for brand-new tables). Without this, `alembic upgrade head` fails
    # with `psycopg.errors.UndefinedObject: type "parametersourcetype"
    # does not exist`. Verified against a live database — see
    # docs/phase2-verification-report.md.
    sa.Enum('SENSOR', 'CONTROLLER', 'PLC', 'CALCULATED', 'MANUAL', 'TBD', name='parametersourcetype').create(op.get_bind(), checkfirst=True)
    op.add_column('machine_parameters', sa.Column('source_type', sa.Enum('SENSOR', 'CONTROLLER', 'PLC', 'CALCULATED', 'MANUAL', 'TBD', name='parametersourcetype'), nullable=False))
    op.add_column('machine_parameters', sa.Column('source_description', sa.String(length=256), nullable=True))
    op.add_column('machine_parameters', sa.Column('sampling_interval_seconds', sa.Float(), nullable=True))
    op.add_column('machine_parameters', sa.Column('expected_data_source', sa.Enum('REAL', 'SIMULATED', 'DATASET_REPLAY', name='datasource'), nullable=False))
    op.create_unique_constraint('uq_machine_parameter_key', 'machine_parameters', ['machine_id', 'parameter_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_machine_parameter_key', 'machine_parameters', type_='unique')
    op.drop_column('machine_parameters', 'expected_data_source')
    op.drop_column('machine_parameters', 'sampling_interval_seconds')
    op.drop_column('machine_parameters', 'source_description')
    op.drop_column('machine_parameters', 'source_type')
    # NOTE: manually added, paired with the manual .create() in upgrade().
    sa.Enum(name='parametersourcetype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_sensor_calibrations_sensor_id'), table_name='sensor_calibrations')
    op.drop_table('sensor_calibrations')
    # ### end Alembic commands ###
